# If want to input None, use !!null

#new additions
useLayers: 7
imgWidth: 256
imgHeight: 256
batch_size: 2
initWeights: True
weightsDir: '/scratch0/sem4/domainAdaptation/code/alexnet/theanoAlexnet/theano_alexnet-master/pretrained/alexnet/parameters_releasing/'
weightFileTag: '_65'
mean_file: /scratch0/sem4/domainAdaptation/code/alexnet/theanoAlexnet/theano_alexnet-master/pretrained/alexnet/img_mean.npy
prob_drop: 0.5


# Directories
weights_dir: ./models/  # directory for saving weights and results

# conv library
lib_conv: cudnn  # or cudaconvnet

snapshot_freq: 1  # frequency of saving weights
print_train_error: True
print_freq: 20  # frequency of printing training error rate
